import os
import requests
import json
import glob

def read_files(patterns):
    content = ""
    for pattern in patterns:
        for file in glob.glob(pattern):
            try:
                with open(file, 'r', encoding='utf-8') as f:
                    content += f"\n--- {file} ---\n{f.read()[:5000]}\n"
            except Exception:
                pass
    return content

def call_gemini(context):
    instructions = f"""
You are a Codebase Suggester. Analyze the provided repository context (README, config files, etc.) and generate exactly ONE high-value improvement suggestion discussion based on the context.
Do not suggest trivial things. Think about architecture, major UX features, security, or robust CI/CD.

Context:
{context[:20000]}

Return ONLY a JSON object with:
{{
  "title": "💡 Suggestion: [Your suggestion title]",
  "body": "Detailed explanation of what should be improved, why it matters, and how to implement it.\\n\\n---\\n> 🤖 *Auto-generated by Gemini Suggester*"
}}
"""
    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
    headers = {"Content-Type": "application/json"}
    data = {"contents": [{"parts": [{"text": instructions}]}]}
    params = {"key": os.environ["GEMINI_API_KEY"]}
    r = requests.post(url, json=data, params=params, headers=headers)
    r.raise_for_status()
    raw = r.json()
    try:
        gemini_text = raw["candidates"][0]["content"]["parts"][0]["text"]
        start = gemini_text.find('{')
        if start >= 0:
            depth = 0
            end = start
            for i, char in enumerate(gemini_text[start:], start):
                if char == '{':
                    depth += 1
                elif char == '}':
                    depth -= 1
                    if depth == 0:
                        end = i
                        break
            if end > start:
                return json.loads(gemini_text[start:end+1])
    except Exception as e:
        print(f"Error parsing Gemini: {e}")
        if 'raw' in locals():
            print(f"Raw response: {raw}")
    return None

def create_discussion(repo, token, title, body):
    # GitHub Discussions requires GraphQL API
    owner, name = repo.split('/')
    headers = {"Authorization": f"bearer {token}", "Content-Type": "application/json"}
    
    # 1. Get repository ID and Discussion Categories
    query = """
    query($owner: String!, $name: String!) {
      repository(owner: $owner, name: $name) {
        id
        discussionCategories(first: 10) {
          nodes {
            id
            name
          }
        }
      }
    }
    """
    r = requests.post("https://api.github.com/graphql", json={"query": query, "variables": {"owner": owner, "name": name}}, headers=headers)
    res = r.json()
    if "errors" in res:
        print(f"GraphQL Error: {res['errors']}")
        return
        
    repo_id = res["data"]["repository"]["id"]
    categories = res["data"]["repository"]["discussionCategories"]["nodes"]
    
    # Try to find 'Ideas' or use the first available category
    category_id = categories[0]["id"]
    for c in categories:
        if "idea" in c["name"].lower() or "general" in c["name"].lower():
            category_id = c["id"]
            break

    # 2. Create Discussion
    mutation = """
    mutation($repoId: ID!, $categoryId: ID!, $title: String!, $body: String!) {
      createDiscussion(input: {repositoryId: $repoId, categoryId: $categoryId, title: $title, body: $body}) {
        discussion {
          url
        }
      }
    }
    """
    vars = {"repoId": repo_id, "categoryId": category_id, "title": title, "body": body}
    r = requests.post("https://api.github.com/graphql", json={"query": mutation, "variables": vars}, headers=headers)
    r.raise_for_status()
    result = r.json()
    if "errors" in result:
        print(f"Error creating discussion: {result['errors']}")
    else:
        url = result["data"]["createDiscussion"]["discussion"]["url"]
        print(f"✅ Discussion created: {url}")

def main():
    repo = os.environ["REPO"]
    token = os.environ["GH_TOKEN"]

    # Gather context from project root
    patterns = ["README.md", "package.json", "requirements.txt", "src/**/*.py", "src/**/*.ts"]
    context = read_files(patterns)
    if not context:
        print("No readable context found.")
        return

    suggestion = call_gemini(context)
    if not suggestion:
        print("No suggestion generated.")
        return

    create_discussion(repo, token, suggestion["title"], suggestion["body"])

if __name__ == "__main__":
    main()
