name: Lint Code Review

on:
  workflow_call:
    inputs:
      files_to_lint:
        description: "Una cadena con los nombres de archivo separados por espacios para analizar"
        required: true
        type: string

jobs:
  lint-code-base:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Super-linter necesita el historial completo para comparar archivos.
          fetch-depth: 0

      - name: Create file filter regex
        run: |
          REGEX=$(echo "${{ inputs.files_to_lint }}" | sed 's/ /|/g')
          echo "LINT_REGEX=$REGEX" >> $GITHUB_ENV

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.2.1
        env:
          # Se necesita el token para que el linter pueda reportar el estado.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          # Filtra super-linter para que solo analice los archivos especificados.
          FILTER_REGEX_INCLUDE: ${{ env.LINT_REGEX }}
