name: Build Feature New
on:
  push:
jobs:
  build-feature:
    runs-on: ubuntu-latest
    outputs:
      changed_files_json: ${{ steps.changed-files.outputs.files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Get changed Python files
        id: changed-files
        run: |
          # Compare with 'develop', get a JSON array of absolute file paths
          FILES=$(git diff --name-only origin/develop...${{ github.sha }} -- '*.py' '*.yml' '*.json' '*.md' | jq -R . | jq -cs .)
          echo "files=$FILES" >> $GITHUB_OUTPUT
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: List installed packages
        run: pip list

  code-review:
    if: ${{ needs.build-feature.outputs.changed_files_json != '[]' }} # Only run if there are changed files
    needs: build-feature
    strategy:
      matrix:
        file: ${{ fromJson(needs.build-feature.outputs.changed_files_json) }}
      fail-fast: false # Allow all jobs to complete even if one fails
    uses: ./.github/workflows/code-review-gemini.yml
    with:
      files_to_analyze: ${{ matrix.file }} # Pass one file at a time
      fail_level: "alta"
    secrets:
      LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
